---
- name: Prepare k3s to the installation
  hosts: server
  become: true
  gather_facts: false
  tasks:
    - name: Get the k3s installation script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s
        mode: "0755"

- name: Install k3s on the server
  hosts: server
  become: true
  gather_facts: false
  tasks:
    - name: Install k3s as the server node
      ansible.builtin.command:
        cmd: "sh /tmp/k3s"
        creates: /etc/rancher/k3s/k3s.yaml
      environment:
        INSTALL_K3S_EXEC: "--flannel-iface=eth1"

    - name: Create directory .kube
      ansible.builtin.file:
        path: ~{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        mode: "u=rwx,g=rx,o="

    - name: Copy config file to user home directory
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~{{ ansible_user }}/.kube/config
        remote_src: true
        owner: "{{ ansible_user }}"
        mode: "u=rw,g=,o="

    - name: Configure default KUBECONFIG for user
      ansible.builtin.lineinfile:
        path: ~{{ ansible_user }}/.bashrc
        regexp: 'export KUBECONFIG=~/.kube/config'
        line: 'export KUBECONFIG=~/.kube/config'
        state: present

    - name: Configure kubectl autocomplete
      ansible.builtin.lineinfile:
        path: ~{{ ansible_user }}/.bashrc
        regexp: '\.\s+<\(kubectl completion bash\)'
        line: ". <(kubectl completion bash)"

- name: Deploy the apps to the cluster
  hosts: server
  gather_facts: false
  tasks:
    - name: "Copy the manifest files to the server"
      ansible.builtin.copy:
        src: "manifests/"
        dest: ~{{ ansible_user }}/manifests
        mode: preserve

    - name: "Apply the manifests to the cluster"
      ansible.builtin.command:
        cmd: "kubectl apply -f manifests"
      changed_when: false
      environment:
        KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
...
