# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-12"

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "4"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.define "aattaliS" do |config|
    config.vm.hostname = "attaliS"
    config.vm.network :private_network, ip: "192.168.56.110"

        config.vm.provision :ansible do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "confs/playbook.yml"
          ansible.limit = "all"
          ansible.groups = {
            "server" => ["aattaliS"],
          }
    end
  end
end
