# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-12"

  vms = [
    { :name => "aattaliS", :ip => "192.168.56.110" },
    { :name => "aattaliSW", :ip => "192.168.56.111" }
  ]

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "1"
  end

  vms.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network :private_network, ip: opts[:ip]

      if opts[:name] == "aattaliSW"
        config.vm.provision :ansible do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "confs/playbook.yml"
          ansible.limit = "all"
          ansible.groups = {
            "server" => ["aattaliS"],
            "workers" => ["aattaliSW"]
          }
        end
      end
    end
  end
end
