---
- name: Create the k3d cluster
  hosts: localhost
  become: false
  tasks:
    - name: Create the k3d cluster
      ansible.builtin.command:
        cmd: "k3d cluster create iot --api-port 6550 -p '8081:80@loadbalancer'"
        creates: ~{{ ansible_user_id }}/.kube/config

- name: Create an ArgoCD stack
  hosts: localhost
  become: false
  vars:
    argocd_url: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
  tasks:
    - name: Create the argocd namespace
      kubernetes.core.k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present

    - name: Install ArgoCD manifests
      kubernetes.core.k8s:
        state: present
        src: "{{ argocd_url }}"
        namespace: argocd
        apply: true

    - name: Wait for ArgoCD resouces to be ready
      kubernetes.core.k8s:
        state: present
        src: "{{ argocd_url }}"
        namespace: argocd
        apply: true
        wait: true
        wait_timeout: 300

    - name: Patch ArgoCD deployment
      kubernetes.core.k8s:
        state: patched
        definition: "{{ lookup('file', 'confs/argocd-patch.yml') }}"

    - name: Apply ArgoCD ingress configuration
      kubernetes.core.k8s:
        state: present
        src: confs/ingress.yml
